spring:
  application:
    name: boot-rabbit-advanced
  rabbitmq:
    host: 192.168.10.129
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    #手动签收
    listener:
      simple:
        acknowledge-mode: manual