server:
  port: 9090
  servlet:
    context-path: /boot
spring:
  application:
    name: springboot-rabbit-demo
  rabbitmq:
    host: 192.168.10.129
    port: 5672
    username: root
    password: 123456
    virtual-host: /